### ISSUE TITLE
Cannot install due to pip error

### ISSUE THREAD

**Issue by francescofact** [pzmarzly/ancs4linux#14]
Hello, i'm trying to install the service with autorun.sh, but the command "pip3 install ." fails everytime
I'm going to upload the error image.
<img width="946" alt="Schermata 2022-08-17 alle 11 52 33" src="https://user-images.githubusercontent.com/28184856/185090013-ecff3901-30b3-490d-adba-60f95b82bbea.png">

**Comment by francescofact** [comment]
solved by running "pip3 install poetry" before running the autorun.sh

**Comment by usarral** [comment]
I have the same error but it doesn't solve it
